// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBohQIWHWwh4yFnkeENlnNuuomuhhh3Us',
    appId: '1:710659845129:web:0b74e4a4e43f97678b5cd8',
    messagingSenderId: '710659845129',
    projectId: 'cryptoapp-ac2e0',
    authDomain: 'cryptoapp-ac2e0.firebaseapp.com',
    storageBucket: 'cryptoapp-ac2e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWxViby7OE5yIqZ9x1DSXkzOi6mciaTZU',
    appId: '1:710659845129:android:f99ccbcd9b5e4dcd8b5cd8',
    messagingSenderId: '710659845129',
    projectId: 'cryptoapp-ac2e0',
    storageBucket: 'cryptoapp-ac2e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvj5fvTc8i6LORWcPzNy-uEvRqcdMFMY',
    appId: '1:710659845129:ios:ab579850a1a2350c8b5cd8',
    messagingSenderId: '710659845129',
    projectId: 'cryptoapp-ac2e0',
    storageBucket: 'cryptoapp-ac2e0.appspot.com',
    iosClientId: '710659845129-nuhhmvm0tq5nsosrjlm1edo7cma02imf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvj5fvTc8i6LORWcPzNy-uEvRqcdMFMY',
    appId: '1:710659845129:ios:ab579850a1a2350c8b5cd8',
    messagingSenderId: '710659845129',
    projectId: 'cryptoapp-ac2e0',
    storageBucket: 'cryptoapp-ac2e0.appspot.com',
    iosClientId: '710659845129-nuhhmvm0tq5nsosrjlm1edo7cma02imf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoapp',
  );
}
